version: '3.9'

services:

  backend:
    container_name: django
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./env_variables.env
    ports:
      - '8000:8000'
    expose:
      - '8000'
    depends_on:
      - redis


  beat:
    container_name: celery-beat
    build: .
    command: celery -A core beat -l INFO
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app


  worker:
    container_name: celery-worker
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app

  redis:
    image: redis
    ports:
      - '6369:6379'

    restart: always
    command: 'redis-server --save --loglevel warning'


  smtp4dev:
    container_name: smtp
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:
