version: '3.9'

services:

  backend:
    container_name: django
    build: .
    command: gunicorn core.wsgi --bind 0.0.0.0:8000 --access-logfile -  --error-logfile -
    volumes:
      - ./backend:/app
      - static-volume:/app/static_files
      - media-volume:/app/media
    env_file:
      - ./env_variables.env
      - ./stage_variables
    expose:
      - '8000'
    depends_on:
      - redis


  beat:
    container_name: celery-beat
    build: .
    command: celery -A core beat --loglevel=debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app


  worker:
    container_name: celery-worker
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app

  redis:
    image: redis
    ports:
      - '6369:6379'
    restart: always
    command: 'redis-server --save --loglevel warning'


  nginx:
    image: nginx
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend
    volumes:
      - ./nginx_configs:/etc/nginx/conf.d
      - media-volume:/home/app/media
      - static-volume:/home/app/static


volumes:
  media-volume:
  static-volume:

