version: '3.9'

services:

  backend:
    user : 1000:1000
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./env_variables.env
    ports:
      - '8000:8000'
    expose:
      - '8000'
